//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Measurement.rc
//
#define IDI_STOPS                       147
#define IDI_POINTS                      208
#define IDD_HDTS                        1000
#define IDC_RIDE_DURATION               1046
#define IDC_BEFORE_RIDE                 1048
#define IDC_CLEAR_AFTER                 1049
#define IDC_CAPTION2                    1121
#define IDC_CAPTION1                    1122
#define IDD_ENTITY_DEBUG                5000
#define IDC_LIST                        5000
#define IDD_TRAINING_SETTINGS           5001
#define IDC_MODE_MANUAL                 5001
#define IDC_MODE_SEMIAUTO               5002
#define IDD_REMAP_SINGLE_TRACK          5002
#define IDD_RETURN_TO_RACE_PART         5003
#define IDD_RETURN_TO_QUALIFICATION     5004
#define IDC_NUM_RIDES                   5004
#define IDD_QUAL_REPAIR                 5005
#define IDD_RIDES_VIEW                  5006
#define IDD_EVENT_DATA                  5007
#define IDR_CONTEXT_MENUS               5008
#define IDC_CHALLENGE                   5009
#define IDB_NORMAL_ICONS                5009
#define IDB_SMALL_ICONS                 5010
#define IDI_TRACK                       5011
#define IDC_GROUPS                      5012
#define IDD_EB_TEST                     5012
#define IDC_RIDES                       5013
#define IDC_WHOLE                       5014
#define IDC_CONTINUE                    5015
#define IDC_END                         5016
#define IDC_RETURN                      5017
#define IDC_PARTS                       5018
#define IDC_CONTINUE_INFO               5019
#define IDC_LIST1                       5020
#define IDC_RESET                       5020
#define IDC_BUTTON1                     5021
#define IDC_EDIT1                       5022
#define IDC_EDIT2                       5023
#define IDC_RACE_PART                   5024
#define IDC_EDIT                        5025
#define IDC_RACE_PART_COMMENT           5026
#define IDC_RIDE_1                      5027
#define IDC_RIDE_2                      5028
#define IDC_RIDE_3                      5029
#define IDC_RIDE_4                      5030
#define IDC_RIDE_5                      5031
#define IDC_RIDE_6                      5032
#define IDC_RIDE_7                      5033
#define IDC_RIDE_8                      5034
#define IDC_RIDE_9                      5035
#define IDC_RIDE_10                     5036
#define IDC_HDTS                        5038
#define IDC_PENALIZATION                5039
#define IDC_LAPS_ELAPSED                5041
#define IDC_TOTAL_LAPS_ELAPSED          5043
#define IDC_UPDATE_LIGHTS               5047
#define IDC_UPDATE_LAPS                 5048
#define IDC_PING                        5049
#define IDC_LAPS                        5050
#define IDC_UPDATE_STATE                5051
#define IDC_STATE                       5052
#define IDC_LIGHTS                      5053
#define IDC_LANE                        5054
#define IDC_PAUSE_DURATION              5055
#define IDS_RANK                        5400
#define IDS_TRACK_SEGMENTS              5401
#define IDS_RACER                       5402
#define IDS_TOTAL                       5403
#define IDS_PENALTY_ABRV                5450
#define IDS_EDITING_OF_RESULTS          5501
#define IDS_ERROR_OPENING_SOUND_OUTPUT  5502
#define IDS_ERROR_OPENING_STM2008       5503
#define IDS_STM2008_NOT_FOUND           5504
#define IDS_CONFIRM                     5702
#define IDS_ARE_DATA_OK                 5703
#define IDS_GO_OVER_SENSOR_X            5704
#define IDS_LANE_X_IS_SENSOR_Y          5706
#define IDS_NTH_GROUP                   5707
#define IDS_RIDE_X_OF_GROUP_Y           5708
#define IDS_OK_TO_CANCEL_RACE_PART_DATA 5709
#define IDS_OK_TO_RESET_INTO_RACE_PART  5710
#define IDS_OK_TO_END_RACEPART          5711
#define IDS_OK_TO_CONTINUE_MEASUREMENT  5712
#define IDS_OK_TO_RESET_WHOLE_RACE      5713
#define IDS_SEGMENT_NUMBER_IN_HEADER    5716
#define IDS_CHOOSE_RACER_TO_EDIT        5718
#define IDS_TOO_MUCH_RACERS_SELECTED    5719
#define IDS_NO_EDIT_RACER_DIDNT_START   5720
#define IDS_ERROR_OPENIN_COMPORT        5722
#define IDS_OK_TO_BEGIN_NEXT_PART       5723
#define IDS_PART_INTERRUPTED_CONTINUE_POSSIBLE 5724
#define IDS_SHEET_GROUP_SEPARATION      5800
#define IDS_SHEET_FINAL_RESULTS         5801
#define IDS_SHEET_TREE_GROUP_SEPARATION 5802
#define IDS_IS_RACE_PART_CORRECTLY_MEASURED 5803
#define IDS_SHEET_TREE_FINAL_RESULTS    5804
#define IDS_SHEET_TREE_LIST_OF_RACERS   5805
#define IDS_SHEET_TREE_GROUP            5806
#define IDS_SHEET_TREE_RACE_PART_RESULTS 5807
#define IDS_COULD_NOT_READ_COMPORT_SETTINGS 5809
#define IDS_TRAINING_NOT_ENOUGH_RIDES   5810
#define IDS_HTML_CHARSET                5811
#define IDS_IMPROPER_TIME_SYNTAX        5812
#define IDS_STM2008_DEAD                5813
#define IDS_STM2008_NOT_CONNECTED       5814
#define IDS_USER_STOPPED_MEASUREMENT    5815
#define IDS_INTERRUPT_MEASUREMENT       5816
#define IDS_FAILED_LOG_DIR_CREATION     5817
#define IDS_COULD_NOT_REPORT            5818
#define IDS_FILL_HUNDREDS               5819
#define IDS_RACE_CAPTION_GROUP          5820
#define IDS_RACE_CAPTION_AUXILIARY_WARMUP 5821
#define IDS_RACE_CAPTION_WARMUP         5822
#define IDS_DEFAULT_PRACTICE_CAPTION    5823
#define IDS_RACE_CAPTION_QUALIFICATION  5824
#define IDS_RACE_CAPTION_SEGMENT        5825
#define IDS_RACE_CAPTION_CURRENT_RESULTS 5826
#define IDS_RACE_CAPTION_CURRENT_TOP10  5827
#define IDS_RACE_CAPTION_NEXT_RACER     5828
#define IDS_RACE_CAPTION_NEXT_RACERS    5829
#define IDS_RACE_CAPTION_RACERS_NEXT_GROUP 5830
#define IDS_RACE_CAPTION_MAIN_LAST_LAP  5831
#define IDS_RACE_CAPTION_MAIN_BEST_LAP  5832
#define IDS_RACE_CAPTION_MAIN_NUM_LAPS  5833
#define IDS_RACE_CAPTION_MAIN_AVGSPD    5834
#define IDS_RACE_CAPTION_MAIN_CURRENT_RANK 5835
#define IDS_RACE_CAPTION_MAIN_LANE      5836
#define IDS_RACE_CAPTION_MAIN_RACER     5837
#define IDS_RACE_CAPTION_MAIN_TOTAL     5838
#define IDS_RACE_CAPTION_MAIN_GAP       5839
#define IDS_RACE_CAPTION_MAIN_PROGNOSIS 5840
#define IDS_RACE_CAPTION_MAIN_POSITION  5841
#define IDS_RACE_CAPTION_TIME_TOSTART   5842
#define IDS_RACE_CAPTION_TIME_TOEND     5843
#define IDS_RACE_CAPTION_TIME_TOWARMUP  5844
#define IDS_RACE_CAPTION_TIME_PRACTICE_ELAPSED 5845
#define IDS_RACE_CAPTION_TIME_WUP_TOEND 5846
#define IDS_RACE_CAPTION_TIME_ENDATTEMPT 5847
#define IDS_RACE_CAPTION_TIME_ENDQUAL   5848
#define IDS_RACE_CAPTION_MAIN_LAST_LAPS 5849
#define IDS_HTML_LIST_OF_GROUPS         5850
#define IDS_HTML_LIST_REGD_RACERS       5851
#define IDS_HTML_RESULTS_GROUP          5852
#define IDS_HTML_FINAL_RESULTS          5853
#define IDS_HTML_VENUE                  5854
#define IDS_HTML_ORGANIZER              5855
#define IDS_HTML_RACE_DIRECTOR          5856
#define IDS_HTML_TRACK_NAME             5857
#define IDS_HTML_NO_GROUPS              5858
#define IDS_HTML_GROUP                  5859
#define IDS_HTML_STARTNO                5860
#define IDS_HTML_RACER                  5861
#define IDS_HTML_RANK                   5862
#define IDS_HTML_LAP_COUNT              5863
#define IDS_HTML_BEST_TIME              5864
#define IDS_HTML_2NDBEST                5865
#define IDS_HTML_BESTLAP                5866
#define IDS_HTML_LAPS                   5867
#define IDS_HTML_PENALIZATION_SHORT     5868
#define IDS_HTML_TOTAL                  5869
#define IDS_HTML_TOTAL_LAPS             5870
#define IDS_HTML_HEATS                  5871
#define IDS_HTML_QUARTER                5872
#define IDS_HTML_SEMIFINAL_SHORT        5873
#define IDS_HTML_FINAL                  5874
#define IDS_HTML_QUALIFICATION_SHORT    5875
#define IDS_HTML_POINTS_SHORT           5876
#define IDS_PART_QUAL                   5877
#define IDS_PART_HEATS                  5878
#define IDS_PART_QUARTER                5879
#define IDS_PART_SEMI                   5880
#define IDS_PART_FINAL                  5881
#define IDS_PART_ERROR                  5882
#define ID_WSF_OPEN                     45800

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        5014
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         5057
#define _APS_NEXT_SYMED_VALUE           5000
#endif
#endif
