//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Data Management.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDS_RACE_TYPE_COMBO             129
#define IDS_DIVIDING_COMBO              130
#define IDB_SMALL_ICONS                 131
#define IDS_POINT_SCHEMA_COMBO          131
#define IDS_DIVISION_UNITS_COMPO        132
#define IDR_CONTEXT_MENUS               133
#define IDS_SELECT_FOLDER               133
#define IDS_SELECT_FOLDER_FOR_DRIVER    134
#define IDS_SELECT_FOLDER_FOR_FOLDER    135
#define IDS_STM_TEST_ERROR              136
#define IDS_STM_TEST_OK                 137
#define IDS_ERROR_CREATING_DATA_FOLDER  138
#define IDB_NORMAL_ICONS                141
#define IDD_DRV_BASIC                   142
#define IDI_RECORD                      143
#define IDD_RS_BASIC                    143
#define IDI_DRV                         144
#define IDI_RACE                        145
#define IDI_GROUP                       146
#define IDD_RS_ADVANCES                 146
#define IDI_STOPS                       147
#define IDD_RS_TIMES                    148
#define IDD_RACE                        151
#define IDI_STAR                        157
#define IDD_RE_START_DATA               158
#define IDD_SETUP_TRACK                 162
#define IDI_TRACK                       163
#define IDD_SETUP_STM                   163
#define IDI_COLORS                      164
#define IDI_STM                         165
#define IDB_SPYTECH_LOGO                168
#define IDD_FIRST_LANES                 178
#define IDI_TOOLS                       181
#define IDD_GROUPS_VIEW                 184
#define IDI_FILETYPE                    188
#define IDD_RS_POINTS                   189
#define IDB_ARROW                       190
#define IDD_TEAM_BASIC                  190
#define IDD_SETUP_SOUND                 191
#define IDI_TEAM_DATA                   200
#define IDI_DRV_DATA                    201
#define IDI_START_DATA                  202
#define IDI_RS                          203
#define IDI_ADVANCES                    205
#define IDI_POINTS                      208
#define IDI_SOUND                       212
#define IDC_ADD                         1002
#define IDC_CLUB                        1006
#define IDC_LICENCE_NUMBER              1007
#define IDC_NAME                        1011
#define IDC_SURNAME                     1012
#define IDC_MEMBER_OF_UNION             1013
#define IDC_PART_CONSI                  1014
#define IDC_NICKNAME                    1014
#define IDC_PART_QUATER                 1015
#define IDC_PART_SEMI                   1016
#define IDC_PART_FINAL                  1017
#define IDC_DATA                        1022
#define IDC_DISTRIBUTION_TYPE           1023
#define IDC_QUAL_QUATER                 1025
#define IDC_QUAL_FINAL                  1027
#define IDC_PART_QUAL                   1028
#define IDC_QUAL_SEMI                   1030
#define IDC_QUATER_BEST                 1031
#define IDC_QUATER_GROUP                1032
#define IDC_SEMI_BEST                   1033
#define IDC_SEMI_GROUP                  1034
#define IDC_CONSI_BEST                  1035
#define IDC_CONSI_GROUP                 1036
#define IDC_CONSI_1                     1046
#define IDC_CONSI_2                     1047
#define IDC_CONSI_3                     1048
#define IDC_ORGANIZER                   1048
#define IDC_QUATER_1                    1049
#define IDC_MIN_MEMBERS                 1049
#define IDC_QUATER_2                    1050
#define IDC_DATE                        1050
#define IDC_QUATER_3                    1051
#define IDC_TRACK_LENGTH                1051
#define IDC_MAX_MEMBERS                 1051
#define IDC_SEMI_1                      1052
#define IDC_MIN_TIME                    1052
#define IDC_SEMI_2                      1053
#define IDC_RACE_TYPE                   1053
#define IDC_SEMI_3                      1054
#define IDC_FINAL_1                     1055
#define IDC_JUDGE                       1055
#define IDC_FINAL_2                     1056
#define IDC_RANKING                     1056
#define IDC_NUMBER                      1056
#define IDC_FINAL_3                     1057
#define IDC_LIST                        1057
#define IDC_PLACE                       1057
#define IDC_QUAL_2                      1058
#define IDC_TRACK_NAME                  1059
#define IDC_QUAL_3                      1059
#define IDC_NUM_LANES                   1061
#define IDC_LANE1                       1062
#define IDC_COM                         1063
#define IDC_LANE2                       1063
#define IDC_LANE3                       1064
#define IDC_LANE4                       1065
#define IDC_DIVISION_TYPE               1066
#define IDC_TYPE                        1067
#define IDC_TYPE2                       1068
#define IDC_TEXT                        1069
#define IDC_OWNER                       1070
#define IDC_LANE5                       1072
#define IDC_LANE6                       1073
#define IDC_CHANGING                    1073
#define IDC_LANE7                       1074
#define IDC_LANE8                       1075
#define IDC_AUTO                        1079
#define IDC_ENTITY1                     1108
#define IDC_NAME1                       1109
#define IDC_ENTITY2                     1110
#define IDC_ENTITY3                     1111
#define IDC_ENTITY4                     1112
#define IDC_MEMBERS_LIST                1112
#define IDC_ENTITY5                     1113
#define IDC_REMOVE                      1113
#define IDC_ENTITY6                     1114
#define IDC_REMOVE_ALL                  1114
#define IDC_ENTITY7                     1115
#define IDC_ENTITY8                     1116
#define IDC_ENTITY9                     1117
#define IDC_UNDIVIDED_LIST              1117
#define IDC_ENTITY10                    1118
#define IDC_GROUPS_LIST                 1118
#define IDC_NAME2                       1119
#define IDC_GROUPS_TEXT                 1119
#define IDC_NAME3                       1120
#define IDC_NAME4                       1121
#define IDC_STATIC2                     1121
#define IDC_NAME5                       1122
#define IDC_STATIC1                     1122
#define IDC_NAME6                       1123
#define IDC_NAME7                       1124
#define IDC_NAME8                       1125
#define IDC_PRINT                       1125
#define IDC_NAME9                       1126
#define IDC_NAME10                      1127
#define IDC_TRACK_MAPPING_ENABLED       1133
#define IDC_REMAP                       1134
#define IDC_UP                          1134
#define IDC_PHYSICAL_1                  1135
#define IDC_PHYSICAL_2                  1136
#define IDC_DOWN                        1136
#define IDC_PHYSICAL_3                  1137
#define IDC_ADD_GROUP                   1137
#define IDC_PHYSICAL_4                  1138
#define IDC_REMOVE_GROUP                1138
#define IDC_PHYSICAL_5                  1139
#define IDC_MEMBERS_TEXT                1139
#define IDC_PHYSICAL_6                  1140
#define IDC_PHYSICAL_7                  1141
#define IDC_PHYSICAL_8                  1142
#define IDC_STATIC3                     1143
#define IDC_POINTS_TYPE                 1144
#define IDC_EDIT                        1147
#define IDC_ENABLE_POINTS               1148
#define IDC_ADD_AFTER                   1149
#define IDC_ADD_BEFORE                  1150
#define IDC_TITLE                       1152
#define IDC_TEST_SOUND                  1156
#define IDC_SELECT_SOUND_CARD           1157
#define ID_NEW_FOLDER                   32779
#define ID_NEW_DRIVER                   32784
#define ID_NEW_TS                       32793
#define ID_NEW_RS                       32794
#define ID_RACE_OPEN                    32797
#define ID_SETUP                        32800
#define ID_RACE_SAVE                    32802
#define ID_RACE_START                   32803
#define ID_ADD_TO_RACE                  32822
#define ID_NEW_TEAM                     32823
#define ID_RACE_SAVE_AS                 32826
#define ID_RACE_NEW                     32827
#define ID_RACE_CLOSE                   32828
#define ID_NEW_GLOBAL_TEAM              32829
#define ID_NEW_GLOBAL_RS                32830
#define ID_RACE_NEXT_PART               32833
#define ID_EXERCISE                     32839
#define ID_EXPORT_DRIVERS               32844
#define ID_IMPORT_DRIVERS               32845
#define ID_EDIT_GROUPS                  32848
#define ID_EDIT_RIDES                   32849
#define ID_RACE_FINISH_PART             32851
#define ID_RACE_RETURN                  32852
#define ID_BRIEF_HELP                   32853
#define IDAE_EXPORT_TO_HTML             32855
#define ID_SOUND_TEST                   32856
#define ID_EXPORT_DRV_FOLDER            32858
#define ID_EB_TEST                      32859
#define ID_GLOBAL_NEW_DRIVER            32861
#define ID_GLOBAL_NEW_FOLDER            32862
#define ID_STM_TEST                     32864
#define IDS_DATA_LOAD_ERROR             61204
#define IDS_DATA_SAVE_ERROR             61205
#define IDS_DRV_IS_ALREADY_IN_RACE      61206
#define IDS_AFXOLEINIT_FAILED           61207
#define IDS_REALLY_AUTODIVIDE           61208
#define IDS_GROUPS_NOT_DONE             61209
#define IDS_MORE_ENTITIES_THAN_ALLOWED  61211
#define IDS_REALLY_NEXT_PART            61212
#define IDS_LESS_ENTITIES_THAN_WANTED   61213
#define IDS_ERROR_DRIVERS_EXPORT        61214
#define IDS_ERROR_DRIVERS_IMPORT        61215
#define IDS_REWRITE_DRIVER              61216
#define IDS_STANDARD                    61218
#define IDS_DATABASE                    61219
#define IDS_RACE_SYSTEMS                61221
#define IDS_DRIVERS                     61222
#define IDS_RACE_CHANGED_SAVE           61223
#define IDS_TWO_HAS_SAME_LANE           61224
#define IDS_PAUSE_CAN_ONE_DRIVER        61225
#define IDS_PAUSE_CAN_X_DRIVERS         61226
#define IDS_DRIVER_CANT_BE_ADDED_NO_TEAMS 61227
#define IDS_DUPLICATE_DRIVER            61229
#define IDS_LETTER_GROUP                61231
#define IDS_MIN_LESS_THAN_MAX           61232
#define IDS_TEAM_WITH_MORE_DRVS_EXISTS  61233
#define IDS_TEAM_EXISTS                 61234
#define IDS_MORE_ADVANCES_THAN_COUNT    61235
#define IDS_RS_EXISTS                   61236
#define IDS_BAD_CHANGING_FORMAT         61237
#define IDS_NUM_RIDES                   61238
#define IDS_NUM_ATTEMPTS                61239
#define IDS_TWO_LANES_SAME_SENSOR       61240
#define IDS_DRV_PROPERTIES              61242
#define IDS_DELETE_DRV                  61243
#define IDS_EMPTY_NAME                  61245
#define IDS_FOLDER_EXISTS               61246
#define IDS_NEW_FOLDER                  61247
#define IDS_RACE_SLASH                  61248
#define IDS_RACE_PROPERTIES             61249
#define IDS_TEAM_FULL                   61250
#define IDS_BUILDING                    61251
#define IDS_QUAL                        61252
#define IDS_CONSI                       61253
#define IDS_QUATER                      61254
#define IDS_SEMI                        61255
#define IDS_FINAL                       61256
#define IDS_FINISHED                    61257
#define IDS_BAD_NUM_OF_LANES            61258
#define IDS_NO_RS                       61259
#define IDS_BAD_TEAM_MEMBER_COUNT       61260
#define IDS_NO_DRIVERS                  61261
#define IDS_REMOVE_DRV_FROM_RACE        61262
#define IDS_DRV_IN_RACE_PROPERTIES      61263
#define IDS_UNKNOWN_TRACK               61264
#define IDS_UNKNOWN                     61265
#define IDS_SETUP                       61266
#define IDS_TEAM_PROPERTIES             61267
#define IDS_DELETE_RS                   61268
#define IDS_RS_PROPERTIES               61269
#define IDS_SOME_CHANGES_AFTER_RESET    61272
#define IDS_RACE                        61273
#define IDS_DUPLICATE_NICKNAME          61274
#define IDS_GROUPS                      61275
#define IDS_SELECT_RS                   61276
#define IDS_SELECT_RS_DETAIL            61277
#define IDS_SELECT_TEAM                 61278
#define IDS_SELECT_TEAM_DETAIL          61279
#define IDS_REALLY_FINISH_PART          61280
#define IDS_RACE_DONE                   61281
#define IDS_BAD_CHANGING                61282
#define IDS_RESET_RACE                  61283
#define IDS_BRIEF_HELP                  61284
#define IDS_HELP                        61285
#define IDS_STM_UNKNOWN_STATE           61286
#define IDS_STM_NOT_CONNECTED           61287
#define IDS_STM_TRACK_IS_OFF            61288
#define IDS_STM_TRACK_IS_ON             61289
#define IDS_POINTS                      61290
#define IDS_RANK                        61291
#define IDS_REMOVE_TEAM_FROM_RACE       61292
#define IDS_DOCUMENTS                   61293
#define IDS_EDITING_RACE_PART_RESULTS   61294
#define IDS_CONTINUE_MEASURE_RACE_PART  61295
#define IDS_START_MEASURE_RACE_PART     61296
#define IDS_SOUND_TEST                  61297
#define IDS_NEW_DRV                     61298
#define IDS_NEW_RACE                    61299
#define IDS_NEW_DRV_IN_RACE             61300
#define IDS_NEW_TEAM                    61301
#define IDS_NEW_RS                      61302
#define IDS_EXIT_EVEN_WITH_DB_LOSS      61303

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        213
#define _APS_NEXT_COMMAND_VALUE         32865
#define _APS_NEXT_CONTROL_VALUE         1164
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
